# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: spanjaan.blogportal::lang.model.comments.recordName

# Model Form Field configuration
form: $/spanjaan/blogportal/models/comment/fields.yaml

# Model Class name
modelClass: SpAnjaan\BlogPortal\Models\Comment

# Default redirect location
defaultRedirect: spanjaan/blogportal/comments

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/blogportal/comments/update/:id
    redirectClose: spanjaan/blogportal/comments

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/blogportal/comments
    redirectClose: spanjaan/blogportal/comments

# Preview page
preview:
    title: backend::lang.form.preview_title
